stages:
  get_data:
    cmd: python -m src.get_data --params params.yaml
    deps:
      - src/get_data.py
      - params.yaml
    outs:
      - data/raw/titanic.csv

  preprocess:
    cmd: python -m src.preprocess_spark --params params.yaml
    deps:
      - src/preprocess_spark.py
      - data/raw/titanic.csv
      - params.yaml
    outs:
      - data/processed/titanic.parquet

  split:
    cmd: python -m src.split_spark --params params.yaml
    deps:
      - src/split_spark.py
      - data/processed/titanic.parquet
      - params.yaml
    outs:
      - data/splits/train.parquet
      - data/splits/test.parquet

  train:
    cmd: python -m src.train_spark --params params.yaml
    deps:
      - src/train_spark.py
      - data/splits/train.parquet
      - data/splits/test.parquet
      - params.yaml
    params:
      - train
      - mlflow
      - data.target
    outs:
      - models/spark_model

  evaluate:
    cmd: python -m src.evaluate --params params.yaml
    deps:
      - src/evaluate.py
      - models/spark_model
      - data/splits/test.parquet
      - params.yaml
    params:
      - train.algorithm
      - data.target
    metrics:
      - metrics.json
