data:
  source: "local"          
  kaggle_competition: "titanic"
  local_raw_dir: "data/raw"
  raw_csv_name: "titanic.csv" 
  test_csv_name: "test.csv"   
  processed_dir: "data/processed"
  splits_dir: "data/splits"
  target: "Survived"

preprocess:
  impute_strategy: "median"
  one_hot_max_categories: 20
  drop_cols: ["PassengerId", "Name", "Ticket", "Cabin"]

split:
  test_size: 0.2
  random_state: 42

train:
  algorithm: ["logreg","random_forest"]
  max_iter: [50, 100, 200]
  reg_param: [0.0, 0.01, 0.1]
  elastic_net_param: [0.0, 0.5, 1.0]
  rf_trees: [10, 50, 100]
  rf_max_depth: [5, 10, 15]

mlflow:
  experiment_name: "titanic-exp-fresh"
  model_name: "titanic_clf"
  metric_to_maximize: "f1"

drift:
  method: "psi"
  psi_threshold: 0.2

retrain:
  enable: true


