services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mlflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mlflow}
      POSTGRES_DB: ${POSTGRES_DB:-mlflow}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    build:
      context: ..
      dockerfile: ops/mlflow/Dockerfile
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql+psycopg2://${POSTGRES_USER:-mlflow}:${POSTGRES_PASSWORD:-mlflow}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-mlflow}
      MLFLOW_ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - mlruns:/mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://mlflow:5000}
      MLFLOW_MODEL_NAME: ${MLFLOW_MODEL_NAME:-titanic_clf}
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    entrypoint: ["/bin/sh", "-c", "chmod +x /wait-for.sh && /wait-for.sh mlflow:5000 -- uvicorn main:app --host 0.0.0.0 --port 8000"]

volumes:
  pgdata:
  mlruns:
